### ISSUE TITLE
OpenDreamKit accepted: send informal announcement

### ISSUE THREAD

**Issue by nthiery** [OpenDreamKit/OpenDreamKit#1]
Please update the following list when you send the announce to some medium
- [X] [sage-devel and sage-combinat-devel](https://groups.google.com/d/msg/sage-devel/cDJlML4L6fs/Wnj2_lP_visJ) (Nicolas)
- [X] [ipython-dev](http://mail.scipy.org/pipermail/ipython-dev/2015-May/016414.html) (Fernando)
- [X] [jupyter](https://groups.google.com/d/msg/jupyter/dyyZcZDn0bs/pIXFJzumT1AJ) (Fernando)
- [X] [LMFDB] (https://groups.google.com/forum/?hl=en-GB#!topic/lmdb/-qUnt8o1UU4) (John)
- [X] [GAP devel](https://mail.gap-system.org/pipermail/gap/2015-May/000035.html) (Alexander)
- [X] [Pythran](https://www.freelists.org/post/pythran/H2020) (Serge)
- [X] [MPIR](https://groups.google.com/forum/#!topic/mpir-devel/weh2y1VFjPY) (Bill)

**Comment by JohnCremona** [comment]
I will send an email to the lmfdb mailing list lmdb@googlegroups.com, after the sage-devel one.

**Comment by alex-konovalov** [comment]
I've sent one to the open GAP development mailing list: https://mail.gap-system.org/pipermail/gap/2015-May/000035.html

**Comment by serge-sans-paille** [comment]
And this one to the pythran mliste:
https://www.freelists.org/post/pythran/H2020

**Comment by alex-konovalov** [comment]
This is a link to the tweet by sagemath: https://twitter.com/sagemath/status/601009096284893185

**Comment by wbhart** [comment]
I've sent a note to mpir-devel:
https://groups.google.com/forum/#!topic/mpir-devel/weh2y1VFjPY

Bill.

**Comment by haraldschilly** [comment]
That tweet did happen automatically when Karl-Dieter posted on Facebook. I did a nicer tweet with hopefully the correct account names: https://twitter.com/sagemath/status/601063941473710080

**Comment by haraldschilly** [comment]
G+ https://plus.google.com/+sagemath/posts/1HB8M1HKgfz

**Comment by Carreau** [comment]
Hey, 

Congratulation for the grant ! Looking forward to see the project building up. 
As I saw you were having draft of logo and I needed a Break from coding on IPython, 
I tried to improved my desing skills, if it can give you some ideas. 

![screen shot 2015-05-24 at 20 48 10](https://cloud.githubusercontent.com/assets/335567/7791526/8b8c6642-0256-11e5-8ee0-c039ef6a1986.png)

**Comment by kohlhase** [comment]
Dear Mattias,

I really like your logo on the left.

The cloud seems a bit massive to me (taking away from the owl/moon
combo. Have you thought about just leaving out the cloud or at least
making it much lighter. I am not sure why there is a cloud at all, I
assume as a metaphor for dream, but the moon already does that.

In any case, the owl/moon/fullmoon combo alone would work very well as
an abbreviate logo (e.g. for favicons).

Even though it dos not spell out "Math" at all, this is the proposal I
like best so far.

Michael

On 25/05/15 05:53, Matthias Bussonnier wrote:
>
> Hey,
>
> Congratulation for the grant ! Looking forward to see the project
> building up.
> As I saw you were having draft of logo and I needed a Break from
> coding on IPython,
> I tried to improved my desing skills, if it can give you some ideas.
>
> screen shot 2015-05-24 at 20 48 10
> <https://cloud.githubusercontent.com/assets/335567/7791526/8b8c6642-0256-11e5-8ee0-c039ef6a1986.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenDreamKit/OpenDreamKit/issues/1#issuecomment-105116985>.
>

-- 
----------------------------------------------------------------------
 Prof. Dr. Michael Kohlhase,        Office: Research 1, Room 168
 Professor of Computer Science  Campus Ring 1, 
 Jacobs University Bremen           D-28759 Bremen, Germany
 tel/fax: +49 421 200-3140/-493140  skype: m.kohlhase   
 m.kohlhase@jacobs-university.de http://kwarc.info/kohlhase 
----------------------------------------------------------------------

**Comment by nthiery** [comment]
Dear Mattias: nice logo! I'll comment on it later. Do you mind reposting it in https://github.com/OpenDreamKit/OpenDreamKit/issues/5 (same for Michael's answer). Thanks!

**Comment by alex-konovalov** [comment]
Dear Matthias, thank you very much for the suggested logo! I very much enjoy the idea of the sun for "O" and the moon for "D", as well as an owl for (mathematical?) knowledge; and the left part by itself would make a nice pictogram indeed! As for the cloud, it may be relevant too because of the use of cloud technologies. 

May I suggest ti try some experiments with colours to make the logo looking less dark, please?
1) more natural (yellow or orange) colour of the sun
2) come lighter colour of the cloud (light blue?). Perhaps not just a solid cloud, but only a contour of it? Also, why the letter "r" is not inside the cloud - may we fit all "reamKIT" inside it? It may be useful to have a version without cloud to compare.
3) The moon would look more natural if it would be white - but that would require a contrast background. How it will look like if the background is blue-ish, the sun is yellow, and the moon, cloud and letters are white, for example?
4) One could also experiment with different owls, see e.g. https://www.iconfinder.com/search/?q=owl&maximum=512 for some inspirations - none of them seem suitable though since we want the moon and the owl to form the letter "D".

Would you be able to find some time to try these ideas, or willing to share the source with others so they could try?

Thanks,
Alexander

**Comment by nthiery** [comment]
On Mon, May 25, 2015 at 04:36:52AM -0700, Alexander Konovalov wrote:
>    Dear Matthias, thank you very much for the suggested logo!

Please move this discussion to #5. Thanks!

				Nicolas
--
Nicolas M. Thiéry "Isil" <nthiery@users.sf.net>
http://Nicolas.Thiery.name/
