### ISSUE TITLE
Don't litter the document structure with symlinks

### ISSUE THREAD

**Issue by embray** [OpenDreamKit/OpenDreamKit#212]
Since 8d4a1b0d57c5bfa4849fdb4f00a0fdb1feeeb451, there are symlinks everywhere to the document class files and style files.

This creates a problem for building the reports on Windows where symlinks aren't really supported without a lot of fidding, and LaTex software for Windows doesn't understand them.

Instead let's just put these files in place, and provide some documentation (for those who don't know how) on how to install the files into one's local texmf (as in https://en.wikibooks.org/wiki/LaTeX/Installing_Extra_Packages#Installing_a_package)

We don't have to go through the trouble of making a package.  In short, people should place the `.cls` and `.sty` files in their local texmf directory under `<texmf>/tex/latex/misc` following the directions for their particular system / software.

CC @nthiery @bpilorget

**Comment by embray** [comment]
Looking at the cls files I realize this proposal currently doesn't work because it tries to include from `../../Proposal` in several places as well, so may this should be put together as a proper package...

**Comment by nthiery** [comment]
On Tue, Jan 24, 2017 at 07:28:05AM -0800, Erik Bray wrote:
>    Looking at the cls files I realize this proposal currently doesn't work
>    because it tries to include from ../../Proposal in several places as
>    well, so may this should be put together as a proper package...

Thanks Erik for investigating this!.

Those ../.. are indeed ugly. IIRC we had worked around some them in
Proposal/ by specifying the tex path in the Makefile; but this
prevents running latex directly which is annoying, especially on
Windows.

One alternative would be to just put copies (instead of links) of the
style files in the directories where they are needed, and have a make
rule to update them when there are changes to the original style
files.

Cheers,
                                Nicolas

**Comment by embray** [comment]
Yes, doing something in the Makefile would make sense.

**Comment by nthiery** [comment]
Done: c3ec983508243499aa0e85d4682c1cf699263023
There still remains a few links in  WP4/D4.2 and  WP4/D4.3, but those are submitted and need not be recompiled, so that's fine.
