### ISSUE TITLE
Sage vs SageMath

### ISSUE THREAD

**Issue by stevelinton** [OpenDreamKit/OpenDreamKit#288]
The current preamble defines \Sage to expand to \software{SAGE}. The Sage project seems to have moved o ver to SageMath pretty much entirely as the name of their software. Should be redefine \Sage to generate \SageMath (which might mess up old documents) or at least add \SageMath for newer documents?

**Comment by nthiery** [comment]
> The current preamble defines \Sage to expand to \software{SAGE}. The Sage project seems to have moved o ver to SageMath pretty much entirely as the name of their software. Should be redefine \Sage to generate \SageMath (which might mess up old documents) or at least add \SageMath for newer documents?

Good point. The convention that has informally emerged is to use
SageMath whenever there may be ambiguity from the context (e.g.
talking to non Math people, beginning of document), and Sage for short
otherwise. In our recent document, we usually use SageMath for the
first occurrence and then Sage. I just added a \SageMath macro in
addition to \Sage so that we do can do both with macros.
