### ISSUE TITLE
D3.4: Personal SageMathCloud : single user version of SageMathCloud distributed with Sage .

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#63]
- **WP3:** [Component Architecture](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP3)
- **Lead Institution:** Université Paris-Sud
- **Due:** 2017-08-31 (month 24)
- **Nature:** Other
- **Task:** T3.6 (#55)

See page 43 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

**Comment by kcrisman** [comment]
@nthiery says this has "basically been implemented" by SMC devs - can someone point me to this?   That would be a huge thing, since then people wouldn't need to be online to edit a `.sagews` file.

**Comment by JohnCremona** [comment]
See https://github.com/sagemathinc/smc/blob/master/src/dev/docker/README.md
which I use to run my own SMC (on a server at the university which I can
also access from elsewhere).

**Comment by kcrisman** [comment]
> See https://github.com/sagemathinc/smc/blob/master/
> src/dev/docker/README.md
> which I use to run my own SMC (on a server at the university which I can
> also access from elsewhere).
>
>
Can this work well on a personal computer too, then?  (I assume so, though
I know nothing about Docker or how that interacts with filesystems - I
don't even know if it's virtualized.)

**Comment by JohnCremona** [comment]
On 6 January 2017 at 16:33, kcrisman <notifications@github.com> wrote:

> > See https://github.com/sagemathinc/smc/blob/master/
> > src/dev/docker/README.md
> > which I use to run my own SMC (on a server at the university which I can
> > also access from elsewhere).
> >
> >
> Can this work well on a personal computer too, then? (I assume so, though
> I know nothing about Docker or how that interacts with filesystems - I
> don't even know if it's virtualized.)
>

I don't see why not, but have not tried and no nothing at all about docker,
I just followed the instructions.

John

**Comment by embray** [comment]
Based on my investigation for #55, I'm not entirely sure that this is a worthwhile goal.  Maybe outside of some narrow testing cases, I'm not convinced that there's much value in running a SMC server on one's personal computer (though it's debatable--I could be convinced otherwise).

What *is* worthwhile, however, is being able to run a local instance, such as in a lab or at a university, of a SMC server that people at that site can access.

The point is that without the ability to collaborate, and without cloud storage, I don't see a lot of value added from running SMC on a personal computer as opposed to using the tools installed locally (terminals, editors, even Jupyter Notebook) directly rather than through SMC.

**Comment by defeo** [comment]
I think there was a confusion at the time of writing the proposal between SMC and its own Sage notebook. What must have been in people's mind at the time was probably a "stripped down version of SMC" that would allow running the SMC Sage notebook locally (at least, that's what was in my mind).
That would still be an interesting goal, in my opinion, but it might be strategically unsound. ODK has mostly moved in a different direction at this point (betting on Jupyter and friends, and implementing converters to migrate from the old notebook system).

**Comment by kcrisman** [comment]
For what it's worth, I think that having something that can run SMC worksheets locally is very valuable.  Otherwise you are a captive audience to the hosted versions.  Whether that falls under ODK auspices is another matter.

**Comment by embray** [comment]
Well, that's partly why I bring it up. I haven't personally used it enough for real projects so I wouldn't be surprised if I don't have a feel for why a personal version would be useful.  To me it seems like overkill for anything I'd want to do offline, and most of the things you can do with it can be done without it just as well if you're working locally.  I see most of the benefits coming very much from the "Cloud" aspect.

In any case, if there were to be an offline, single-user version of it one would want to simplify things somewhat--disable features like authentication and chat for example.   Make the overall experience more like running the Jupyter Notebook locally.

**Comment by defeo** [comment]
> Well, that's partly why I bring it up. I haven't personally used it enough for real projects so I wouldn't be surprised if I don't have a feel for why a personal version would be useful. To me it seems like overkill for anything I'd want to do offline, and most of the things you can do with it can be done without it just as well if you're working locally. I see most of the benefits coming very much from the "Cloud" aspect.

By talking to end users (I mean students as well as researchers), I
realized that one of the features they really like is the
click'o'matic UI, where they can easily find mathematical functions
and objects, classified by domain, through the drop-down menus. It may
look minor to us power-users, but let's not forget that end users
seldom use tab-completion, and even less they read manual.

> In any case, if there were to be an offline, single-user version of it one would want to simplify things somewhat--disable features like authentication and chat for example. Make the overall experience more like running the Jupyter Notebook locally.

That's why I was suggesting that it might be strategically unsound to
have OpenDreamKit do this: the amount of work required to strip down
the interface risks diluting our efforts too much. I think you have a
better view on this than any of us.

It also gives SMC an (additional) commercial advantage over a local
installation, which, at this point in the development of the company,
we may want to consider before taking it away.

**Comment by embray** [comment]
> By talking to end users (I mean students as well as researchers), I
realized that one of the features they really like is the
click'o'matic UI, where they can easily find mathematical functions
and objects, classified by domain, through the drop-down menus. It may
look minor to us power-users, but let's not forget that end users
seldom use tab-completion, and even less they read manual.

This is a feature specifically of the new Sage worksheet in SMC though, which in principle could be separated out from the rest of SMC.  As you yourself said, that might not be worthwhile though if we are focusing our efforts on Jupyter.

Now, if Jupyter Notebook could provide a way for specific kernels (for example) to provide their own menus in the UI, then that would mostly fulfill that use case.

**Comment by nthiery** [comment]
On Tue, Feb 14, 2017 at 03:20:57AM -0800, Erik Bray wrote:
>    Based on my investigation for [1]#55, I'm not entirely sure that this
>    is a worthwhile goal. Maybe outside of some narrow testing cases, I'm
>    not convinced that there's much value in running a SMC server on one's
>    personal computer (though it's debatable--I could be convinced
>    otherwise).
> 
>    What is worthwhile, however, is being able to run a local instance,
>    such as in a lab or at a university, of a SMC server that people at
>    that site can access.
>
>    ...

Thanks Erik for bringing that up and everybody for the comments.

At the time of the proposal writing, my understanding of that
deliverable was that the deployment of a full SMC instance was a
serious challenge and that it was useful to set an intermediate goal;
in that case making it "easy" to deploy SMC on a single machine,
possibly even just for a single person.

Looking back at it, and as pointed by Erik, the "single person" aspect
reduces quite some the use cases: much, though not all, of the added
value of SMC is about collaboration! On the other hand making it easy
to setup a a local instance would be a very worthwhile goal. Even with
the "single machine" restriction this could plausibly cover quite a
few use cases: a class room, a team of researchers, a small lab.

So, what about making this deliverable into «Easy to deploy single
machine SMC» ?

- Can we consider that the existing SMC (docker) container already
  takes care of the old «Personal SMC» goal?

- Is the container approach the right one?

- How much additional work would it be to reach the new goal?

- Is it indeed much simpler to deploy SMC on a single machine rather
  than a cluster?

- Or does the difficulty actually come from the potentially desirable
  integration with the local infrastructure (e.g. using the
  authentication or disk storage services from one's university)?

- How big a group of users can one hope to cater for with a single
  machine (say 32 cores and a bunch of GB of memory)?

- Altogether, is it worth the effort?


By the way: +1 for discussing with the Jupyter people how one could
have, in Jupyter, something like kernel-specific menus for the most
common commands; that's indeed a nice feature for newcomers.

Cheers,
                                        Nicolas

**Comment by embray** [comment]
> So, what about making this deliverable into «Easy to deploy single machine SMC» ?

Yes, I think that makes more sense.  In fact, William tells me that the new Kubernetes-based configuration for SMC is not going to be open source, which makes sense for a number of reasons. But really it is not needed for anything more than a large scale installation anyways.  It is definitely much easier to deploy SMC running on a single machine, and that is still adequate for uses cases like those you mentioned: "a class room, a team of researchers, a small lab".

> Can we consider that the existing SMC (docker) container already takes care of the old «Personal SMC» goal?

I think so. In fact, I found that to be the *only* easy way to get SMC up and running.  For some use cases one might want to make small modifications to the container configuration (not using a self-signed SSL certificate, for example).  We might also want to work with SMC to make it easier to change the "branding" of such personal installations, so that it's more clearly distinct from the real "cloud.sagemath.com".  Will have to ask William what he thinks about this.

> Is the container approach the right one?

Yes, I think so. As above, it's by far the easiest way to do this.

> How much additional work would it be to reach the new goal?

Other than the "branding" issue mentioned above, there are a few known issues with the Docker image: https://github.com/sagemathinc/smc/issues?q=is%3Aopen+is%3Aissue+label%3AA-docker  Not all of them are blockers.  Some of the security issues are worth considering, but are also less crucial for the use case small local installations used by teams that are working on the same projects.

> Is it indeed much simpler to deploy SMC on a single machine rather than a cluster?

Yes, much.

> Or does the difficulty actually come from the potentially desirable integration with the local infrastructure (e.g. using the authentication or disk storage services from one's university)?

I don't know if the site-specific authentication use case has been considered (for obvious-enough reasons).  Though SMC is using [PassportJS](http://passportjs.org) for authentication, and with a little bit of refactoring I think could easily accept "authentication plugins" for any auth method that can be packaged as a Passport strategy.  It's not there yet, but not too far off either.  The use or non-use of Docker doesn't have much impact here.

The storage aspect might not present particular difficult either.  If using Docker, one would store project data in a volume, and with recent versions of Docker could use one of many volume plugins (or write one's own) for different storage backends.

> How big a group of users can one hope to cater for with a single machine (say 32 cores and a bunch of GB of memory)?

That's something William would have to answer.  Obviously it depends on how they're using it too.

> Altogether, is it worth the effort?

That obviously depends widely on the case.  If the infrastructure / knowledge to support a web service locally exists and doesn't require too much overhead, than maybe.  Or if work is being done on sensitive data that one wouldn't want to put on the internet.

**Comment by embray** [comment]
Having played more with and learned more about the Sage Worksheets in SMC it actually has a somewhat different philosophy, UI-wise, than Jupyter.  So it's not fair to say that the "menus" are the only difference.  I have no opinion about if or how it should factor into ODK's goals though.

**Comment by bpilorget** [comment]
@defeo  This deliverable is officially due for 31/08/2017. Can you please report on the progress you have achieved?
Thanks in advance

**Comment by embray** [comment]
This deliverable was specifically singled out in the reviewer report as one that has been overcome by events and should have its resources reallocated.

**Comment by slel** [comment]
Anyone can now install a single-user version of CoCalc using Docker.
The source files and the docker image are at
- https://github.com/sagemathinc/cocalc-docker
- https://hub.docker.com/r/sagemathinc/cocalc/

**Comment by embray** [comment]
I think it's still a bit odd to call the existing CoCalc Docker image a "single-user" version.  It's still technically a multi-user system, and one has to "register" and "account" in it, and also manually add one's self as an "administrator" on the server to really use it.  It's not equivalent to, say, firing up a Jupyter Notebook server on one's machine.

This makes some sense, of course, as CoCalc/SMC was conceived of as a multi-user system anyways.  But it might be nice, for the sake of just working on a few projects locally, to have a truly "single-user" mode for CoCalc that obviates those extra steps (especially given that the Docker image is inherently insecure for multi-user use--which is not to say it's not still useful for a small group of trusted people working together).

**Comment by defeo** [comment]
I confirm what @embray said: this deliverable was officially scapped. See 6.2 in https://github.com/OpenDreamKit/Participants/blob/master/ReportingPeriod1/WorkPlanRevisions.tex

**Comment by nthiery** [comment]
>    I confirm what [1]@embray said: this deliverable was officially
>    scapped. See 6.2 in
>    [2]https://github.com/OpenDreamKit/Participants/blob/master/ReportingPe
>    riod1/WorkPlanRevisions.tex

Note that the above proposal has not been officially accepted yet. But
yes, that part was suggested by the reviewers, so it's unlikely that
it would not be accepted.

**Comment by bpilorget** [comment]
Canceled in 3rd amendment to the contract as work was done by the community
