### ISSUE TITLE
D3.6: Open package repository for Sage

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#65]
- **WP3:** [Component Architecture](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP3)
- **Lead Institution:** Université de Versailles Saint-Quentin
- **Due:** 2017-08-31 (month 24)
- **Nature:** Other
- **Task:** T3.3 (#52)
- **Proposal:** [p. 43](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf)

SAGE has a long history of integrating and distributing large mathematical libraries/software as a whole, with relatively few attention given to defining and exposing interfaces. Component re-usability is not a main focus for the SAGE community, at the same time the non-standard and relatively underused package system discourages writing and maintaining autonomous libraries. These factors have contributed to make the SAGE distribution what is usually described as a “monolith” (SAGE library code alone, not counting included libraries, makes up for 1.5M lines of code and documentation), hard to distribute, to maintain, to port, and to develop with. On the other hand, GAP has been distributing community-developed “GAP packages” for a long time, but faces now fragmentation issues, at the code and at the community level. The rudimentary package system adds more technical difficulties to GAP’s development model. 

Both models reach the limits of their scalability, and a synthesis is very much needed. Our first experiment will be to enhance SAGE ’s package system (D3.6), enough to support an open repository of user-contributed code, in the same spirit of modern systems such as Julia (http://pkg.julialang.org/ ) or PyPI (https://pypi.python.org/).

**Comment by embray** [comment]
@nthiery and I have talked a bit before about making a package template for Sage related projects, and there has already been some work on that I think, though I forget where.  I've mentioned before that [cookiecutter](https://github.com/audreyr/cookiecutter) might be a good system to use for easy bootstrapping / customization of a Sage-related package.  

I bring this up again, now, because the Astropy project has recently switched to using cookiecutter for its (fairly complex) package template for Astropy-affiliated packages, as described here: https://github.com/astropy/astropy-APEs/blob/master/APE12.rst

This would be worth looking at as a non-trivial example of using cookiecutter for package templating.

**Comment by slel** [comment]
@embray wrote:
> @nthiery and I have talked a bit before about making a package template
> for Sage related projects, and there has already been some work on that I think,
> though I forget where.

A summary is in a Sage-devel discussion:
https://groups.google.com/d/topic/sage-devel/H1PfTgSPgd0/discussion

Suggestion: renaming `sage-sample` to `sage-package-template` and
moving it from github.com/nthiery to github.com/sagemath would
probably make it easier to discover (making sure to use the appropriate
renaming procedure on github so that a redirection is set up).

**Comment by bpilorget** [comment]
@defeo  This deliverable is officially due for 31/08/2017. Can you please report on the progress you have achieved?
Thanks in advance

**Comment by defeo** [comment]
This deliverable was officially merged in D3.10 (#59), due M48, in the latest work plan revision. See https://github.com/OpenDreamKit/Participants/blob/master/ReportingPeriod1/WorkPlanRevisions.tex

**Comment by bpilorget** [comment]
#65 was merged in #59 after the 3rd amendment to the contract
