### ISSUE TITLE
D3.7: One-click install Sage distribution for Windows with Cygwin 32bits and 64bits

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#66]
- **WP3:** [Component Architecture](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP3)
- **Lead Institution:** Université Paris-Sud
- **Due:** 2017-08-31 (month 24)
- **Nature:** Other
- **Participants:** @embray, @jpflori, @defeo, @wbhart, ...
- **Proposal:** [p.43](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf)
- **[Blog post](http://opendreamkit.org/2017/10/11/SageWindows/)**
- **[Final report](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/WP3/D3.1/report-final.pdf)**

One of the main tasks of WP3 is concerned with portability of the
software components of OpenDreamKit. Most components are developed in
UNIX environments (Linux and/or OS X), and porting them to other
platforms, most importantly the Windows operating system, is usually a
challenge.

Although UNIX-like systems are popular among open source software
developers and some academics, the desktop and laptop market share of
Windows computers is estimated to be more than 75\% and is an important
source of potential users, especially students.

Some OpenDreamKit components have been supporting Windows for a long
time. However Windows support for SageMath, the largest of them, has
been elusive for more than 10 years. This is particularly challenging,
not so much because of the Sage Python library (which has some, but
relatively little system-specific code). Rather, the challenge is in
porting all of SageMath's 150+ standard dependencies, and ensuring that
they integrate well on Windows, with full Sage's test suite fully passing.

Thus, finally bringing Windows support to the SageMath distribution has
the added benefit of producing working Windows versions of all the CAS's
and other software SageMath depends on, such as GAP, Singular, etc.

We are happy to report that, thanks to OpenDreamKit's efforts, and in
particular thanks to Erik Bray's work at Université Paris-Sud, starting from
version 8.0 of SageMath, released on July 21, 2017, a native Windows 64 bit
installer based on Cygwin has been made available for all users from
[Sage's download page](https://www.sagemath.org/download-windows.html). This is now the recommended way to install SageMath on Windows
platforms.

Originally, the deliverable also had the goal of delivering an installer
for Windows 32-bit based on Cygwin. Unfortunately, this goal was not
achieved due to technical obstacles that we shall briefly explain at
the end of the report. Fortunately, the market share for Windows
32-bit is ever shrinking, and we estimate that the lack of a 32-bit
installer has a very low impact on SageMath's user base.

References:
- Trac pages tracking the current status of [Sage on Cygwin](http://trac.sagemath.org/wiki/CygwinPort) and [Cygwin64](http://trac.sagemath.org/wiki/Cygwin64Port) (lead: @jpflori)
- [Thread on sage-devel initiated by @wbhart on using alternatively MSYS2 for porting Sage on Windows](https://groups.google.com/d/msg/sage-devel/3tKSfcbhlDM/fWFa-X1WBwAJ)
- Experimentation with a [one click installer using a docker image](https://github.com/sagemath/docker-images/issues/1)
- [Notes](https://wiki.sagemath.org/days77/packaging#Windows) from Sage Days 77 workshop (Cernay 2016) on packaging and portability

**Comment by nthiery** [comment]
I updated the summary comment above with references & such.

I don't have an opinion on whether it's better to use Cygwin or MSYS2.  If it turns out that MSYS2 is technically more appropriate, I am pretty sure it's an easy negotiation with our project officer to deliver that instead.

**Comment by wbhart** [comment]
The conclusion of that discussion was that MSYS2 is no more appropriate
than Cygwin. They both provide a roughly isomorphic posix layer. The only
advantage of MSYS2 in real terms as far as ODK is concerned is its command
line package manager.

What is ultimately needed for Sage is a port to MinGW, not MSYS2 or Cygwin.
However, it is not feasible to make this an aim of the ODK project.

I will be working on porting more mathematical libraries to MinGW, but this
is much more involved than porting to Cygwin. And I'm not doing that as
part of ODK. It's an independent goal.

Bill.

**Comment by embray** [comment]
I spoke with @nthiery about this when I visited a a couple months ago, but I agree that relying on Cygwin for Windows builds is not an appropriate way forward--he suggested that the "Cygwin" aspect of this task is less relevant than the "distribution for Windows" part.

I would prefer to get seamless builds on Windows working in MinGW-w64 (and/or 32-bit MinGW depending on what the challenges are), at first using gcc, but eventually using MSVC as well.  Whatever ends up working, this will be used to provide binary wheels for Windows, and will also work toward providing conda packages as well.

**Comment by wbhart** [comment]
The following work on MinGW-w64:

MPIR and GMP
MPFR
Flint
Antic (not relevant for Sage)
libpari

OpenBLAS is known to work
Python-2.7 was ported by the MSYS2 devs

We have Arb working but currently have some test failures to sort out

There was some talk a while back about porting Singular to MinGW-w64. We
had a candidate in mind to hire to work on this, but he never replied to
our emails after initially showing interest. I will try once more to follow
up on this, but am not hopeful.

Gap will be difficult to port due to quite a bit of Posix stuff. One of the
MSYS2 developers was interested in the challenge of porting Gap to
MinGW-w64 (and some other mathematical software too), but didn't really
have time to work on it at the moment.

Bill.

**Comment by embray** [comment]
Forgive my naivete, since I'm entirely new to Sage.  But from things I've picked up here and there it sounds like GAP is by far the worst offender in terms of compilation difficulty.  @nthiery Should I expect to spend any time contributing directly to GAP to improve its portability?

**Comment by nthiery** [comment]
On Tue, Dec 29, 2015 at 12:49:29PM -0800, Erik Bray wrote:
>    Forgive my naivete, since I'm entirely new to Sage. But from things
>    I've picked up here and there it sounds like GAP is by far the worst
>    offender in terms of compilation difficulty. [1]@nthiery Should I
>    expect to spend any time contributing directly to GAP to improve its
>    portability?

If there is a consensus that mingw64 is the way to go, then you and
Jeroen have a white card on how to best use your ODK-funded time to
reach that goal, either by finding people to take on some of the
tasks, or taking them on yourself.

In any cases, feel free to experiment with different options to build
a personal opinion on the matter.

				Nicolas

PS: Speaking of GAP, it would be nice if you could attend the upcoming
GAP-Sage days (if your moving around allows for it):

        http://gapdays.de/gap-sage-days2016/

@jdemeyer: would you have a chance to attend too?

**Comment by nthiery** [comment]
Just one comment about Cygwin vs MinGW/MSys2: the primary goal is to have a solid long-term solution. However a secondary goal is to have a working solution in the short run (even if it has some limitations). This might be a case for pursuing the original Cygwin 32bit goals, given that @jpflori estimated this could be achieved within a few months; and we can hope that most of the work spent there is needed anyway for MinGW.

**Comment by nthiery** [comment]
Another note: we will organize a developers workshop in Cernay (near Orsay) sometime this spring, with topics revolving around portability, packaging, sphinx, ... That should be a good occasion for brainstorming and settling on a strategy. We will post a poll sometime soon to choose dates so that as many of you can come!

**Comment by mikecroucher** [comment]
@wbhart I've never ported anything to MinGW-w64 but am curious. Is there a list of libraries / packages for which ports would be desirable anywhere?

**Comment by jdemeyer** [comment]
> @jdemeyer: would you have a chance to attend too?

I could come except for the last day (there is an exam of a computer algebra course that I teach). However, I know essentially nothing about GAP, so I'm not sure if it would be useful. If you think that I should come, let me know.

Note that I will go to the PARI atelier the week before.

**Comment by jpflori** [comment]
@jdemeyer: I'll be at the PARI workshop as well so we can discuss there.


2015-12-30 11:00 GMT+01:00 jdemeyer <notifications@github.com>:

> @jdemeyer <https://github.com/jdemeyer>: would you have a chance to
> attend too?
>
> I could come except for the last day (there is an exam of a computer
> algebra course that I teach). However, I know essentially nothing about
> GAP, so I'm not sure if it would be useful. If you think that I should
> come, let me know.
>
> Note that I will go to the PARI atelier the week before.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenDreamKit/OpenDreamKit/issues/66#issuecomment-167971360>
> .
>



-- 
Jean-Pierre Flori

**Comment by nthiery** [comment]
@jdemeyer: thinking twice about it, it's really up to whatever you think is most productive for you.
Cheers,

**Comment by rgommers** [comment]
Hi all, someone just pointed me to this issue. It looks like you're thinking in the same direction as we are doing for Numpy and the Scipy Stack. In summary:

- Problem is that we don't have a free compiler toolchain to build the Scipy stack, and hence no numpy/scipy/... Windows wheels on PyPi.
- Solution will be to use a MinGW-w64 based static compiler toolchain that will be easily installable and will be able to build the whole Scipy stack in a way compatible with standard python.org Python builds.
- [Proposal for funding](http://mingwpy.github.io/proposal_december2015.html) (phases 1 and 2 are accepted) and [MingwPy project](http://mingwpy.github.io)
- Announcement on the Numpy mailing list of today is [here](http://article.gmane.org/gmane.comp.python.numeric.general/62207).

It would be interesting to hear if you think there's synergy between the plans for MingwPy and what you need for Sage.

FYI @njsmith, @matthew-brett, @ogrisel, @carlk

**Comment by jdemeyer** [comment]
About the Windows port:

First of all, the goal should be to have a *fully* working Sage, not just a few working packages. Therefore, we should try to "port" as little as possible. That is, I would go for whatever solution requires the least changes to the codebase of Sage and its included packages. This most likely implies using Cygwin instead of MinGW and GCC instead of MSVC.

**Comment by njsmith** [comment]
Before embarking down the cygwin road, I'd consider very carefully whether the best solution might not just be to deliver a one-click executable that spawns a linux vm image and then opens a native browser window pointing to a notebook running inside it. That'd probably be much easier/more maintainable than going to cygwin, and cygwin is not terribly far from a VM setup itself.

**Comment by jdemeyer** [comment]
> Before embarking down the cygwin road, I'd consider very carefully whether the best solution might not just be to deliver a one-click executable that spawns a linux vm image and then opens a native browser window pointing to a notebook running inside it.

That more or less already exists (although it uses a browser inside the VM instead of a native browser for reasons I don't understand)

> cygwin is not terribly far from a VM setup itself.

Huh? I know this is probably meant as hyperbole, but I don't see how Cygwin could even remotely be seen as a VM.

**Comment by dimpase** [comment]
It appears that indeed GAP is one of the bigger barriers towards Sage running on MinGW, although it's a relatively small part of code that needs tricky work (memory allocation/GC).

I am not sure if ECL can be built on MinGW (they certainly have native Windows port, but it's geared towards MSVC). (But this is most probably not hard). 

I am also not sure how good is (C)Python on MinGW, given the need to support Cython and loadable modules well. Perhaps Python experts can comment on this.

**Comment by wbhart** [comment]
On 2 January 2016 at 13:45, jdemeyer <notifications@github.com> wrote:

> Before embarking down the cygwin road, I'd consider very carefully whether
> the best solution might not just be to deliver a one-click executable that
> spawns a linux vm image and then opens a native browser window pointing to
> a notebook running inside it.
>
> That more or less already exists (although it uses a browser inside the VM
> instead of a native browser for reasons I don't understand)
>
> cygwin is not terribly far from a VM setup itself.
>
> Huh? I know this is probably meant as hyperbole, but I don't see how
> Cygwin could even remotely be seen as a VM.
>
I think he just means that Cygwin doesn't really give you native Windows
applications, it's a bulky system you have to download and put on your
system, and everything runs inside that system. I don't think he was making
a technical distinction.

**Comment by dimpase** [comment]
On 2 January 2016 at 15:32, wbhart <notifications@github.com> wrote:

> On 2 January 2016 at 13:45, jdemeyer <notifications@github.com> wrote:
>
> > Before embarking down the cygwin road, I'd consider very carefully
> whether
> > the best solution might not just be to deliver a one-click executable
> that
> > spawns a linux vm image and then opens a native browser window pointing
> to
> > a notebook running inside it.
> >
> > That more or less already exists (although it uses a browser inside the
> VM
> > instead of a native browser for reasons I don't understand)
> >
> > cygwin is not terribly far from a VM setup itself.
> >
> > Huh? I know this is probably meant as hyperbole, but I don't see how
> > Cygwin could even remotely be seen as a VM.
> >
> I think he just means that Cygwin doesn't really give you native Windows
> applications, it's a bulky system you have to download and put on your
> system, and everything runs inside that system. I don't think he was making
> a technical distinction.
>

This is not really correct. You might care to check a Windows installation
of GAP to see that, well, it does need one or two extra dlls to install,
but otherwise it is something that you may e.g. run in native command line
window, and the download is small (not much bugger than a Linux binary)

Needless to say, having Cygwin as a development environment is another
story, it is not small and has its quirks --- but so is MSVC, too...

**Comment by wbhart** [comment]
On 2 January 2016 at 16:58, Dmitrii Pasechnik <notifications@github.com>
wrote:

> On 2 January 2016 at 15:32, wbhart <notifications@github.com> wrote:
>
> > On 2 January 2016 at 13:45, jdemeyer <notifications@github.com> wrote:
> >
> > > Before embarking down the cygwin road, I'd consider very carefully
> > whether
> > > the best solution might not just be to deliver a one-click executable
> > that
> > > spawns a linux vm image and then opens a native browser window pointing
> > to
> > > a notebook running inside it.
> > >
> > > That more or less already exists (although it uses a browser inside the
> > VM
> > > instead of a native browser for reasons I don't understand)
> > >
> > > cygwin is not terribly far from a VM setup itself.
> > >
> > > Huh? I know this is probably meant as hyperbole, but I don't see how
> > > Cygwin could even remotely be seen as a VM.
> > >
> > I think he just means that Cygwin doesn't really give you native Windows
> > applications, it's a bulky system you have to download and put on your
> > system, and everything runs inside that system. I don't think he was
> making
> > a technical distinction.
> >
>
> This is not really correct.


Yes it is. Cygwin involves a shell, posix emulation layer, a distribution
and much more besides. It has its own ABI and by and large you don't link
against system provided libraries, but libraries that have been specially
compiled for Cygwin, and so on. It's a Linux on Windows.


> You might care to check a Windows installation
> of GAP to see that, well, it does need one or two extra dlls to install,
> but otherwise it is something that you may e.g. run in native command line
> window, and the download is small (not much bugger than a Linux binary)
>

You are talking about deployment of a single (relatively small)
application, not a working ecosystem. Yes, you can deploy a single
application with just a few extra dlls. But it's still effectively
insulated from the rest of the Windows system by those dlls. If you want to
use the application as part of an ecosystem, you need the rest of the
Cygwin ecosystem. There is little or no advantage over a VM.


>
> Needless to say, having Cygwin as a development environment is another
> story, it is not small and has its quirks --- but so is MSVC, too...


Cygwin, as a development environment and an ecosystem is a Linux, not a
Windows. And many concepts don't map well and aren't emulated well,
especially for large projects.

MinGW-w64 compiles native Windows applications and they don't suffer from
the rebasing issues or the BLODA, etc.

Moreover, Cygwin is so bad for developers that they are probably better off
doing their Cygwin development on a Linux box, not directly on Windows.

Bill.

**Comment by wbhart** [comment]
There's a good description of just what Cygwin does to provide a working
environment for Cygwin applications within Windows starting with section
1.6 of [1].

In short, Cygwin has a different system to Windows for:

* line endings (also requires violation of the posix standard)
* filenames and directory system
* PID's
* user management
* address space management
* ABI
* system calls (posix emulation vs Win32)

Morevover it suffers from:

* dll base address collisions which can only be resolved using the
rebaseall tool
* problems with Windows address space layout randomization, which simply
lead to application failure
* dll injection by a "Big List of Dodgy Apps" which can only be fixed by
removing the apps

And there are a number of other features that don't implement cleanly on
top of Win32: signals, select, sockets.

Cygwin has its own library formats which are not accessible from Windows
system apps or libraries. It's very much a system within a system, not
completely unlike a VM.

MinGW-w64 on the other hand is basically a C compiler for the Windows
system which supports GNU conventions and is Open Source. Its goal is to
provide an Open Source compiler for Windows, not to provide a Linux on
Windows. MinGW simply aims to provide a minimalist GNU toolchain on
Windows, not to provide a Linux on Windows.

There's a world of difference between the two approaches. I personally have
no firm opinion about whether a port of Sage to native Windows is desirable
within the framework of ODK. A Cygwin port is not too much work, since JP
and others have already done so much. It would be an achievement. But it
will always be limited by being Cygwin, and will be pretty useless for
Windows developers.

A port to MinGW-w64 would be really impressive, but a lot of hard work.
Whether it's achievable depends on whether we have the manpower, whether
the will exists, the goals of the project and whether the technical
expertise exists. I guess one also needs to consider whether it is worth
it. Would such a port really increase the Windows usership of our
mathematical software? Would it increase the number of skilled Windows
developers available to us? Would it be sustainable? Would the individual
upstream projects support it?

Regarding MSVC. It's nowadays a very small step from MinGW-w64 support to
MSVC support. The latter provides a very fast and quite capable C++
compiler (not a C compiler). It doesn't however provide inline assembly
support on Windows 64.

And there is no way that a project as large as Sage could be managed via
Visual Studio. (Loading the Visual Studio files for Flint alone on the
first run takes 15 minutes, due to some XML creation that it does!!)

This leaves the question of what toolchain to use for development. On that
issue, I'm not an expert, so don't have anything to add. But otherwise, 90%
of the work in porting Sage to MSVC would be done by porting to MinGW-w64.

Something else to consider: very few individuals have shown an interest in
actually doing the work of porting mathematical software to MSVC. Brian
Gladman is the only person I know of that has put significant effort into
this over the years and that via an automated Python tool that generates
visual solution files. There has been one other individual who has done
some work recently, but they have indicated that they don't have time to
contribute to it on an ongoing basis. Brian clearly can't manage any more
projects than he already is. So the question is, where would the labour
come from to manage an MSVC build?

Bill.

[1] https://cygwin.com/cygwin-ug-net/cygwin-ug-net.pdf

**Comment by dimpase** [comment]
Building Sage by MSVC  is particularly problematic due to lack of a compatible (and free) fortran compiler, needed in particular for R. R devs use mingw-w64 to build R for Windows 64. And same is true for scipy/numpy people, if I understood the comment above right.

**Comment by serge-sans-paille** [comment]
> And same is true for scipy/numpy people

And for pythran people too ;-)

**Comment by njsmith** [comment]
To clarify: as of today, scipy/numpy do not use mingw-w64 to build for windows, because as of today, mingw-w64 doesn't generate binaries that are compatible with MSVC-built binaries, and the python.org standard on windows is that python itself should be built with MSVC. @rgommers's comment about is describing our plans to fix that, so that in the future we will be able to use mingw-w64 to build scipy/numpy, and use this to distribute binaries that *are* compatible with MSVC-built binaries.

**Comment by slel** [comment]
Related concerns appeared recently on the [fricas-devel mailing list](https://groups.google.com/forum/#!forum/fricas-devel)
where the following themes were discussed
- Docker image
- Jupyter kernel
- SageMathCloud integration
- Windows build

See in particular:
    https://groups.google.com/d/topic/fricas-devel/RMZyvd-xvTw/discussion
    https://groups.google.com/d/topic/fricas-devel/7ijc1igZVI0/discussion

**Comment by bpilorget** [comment]
@defeo This deliverable is officially due for 31/08/2017. Can you please report on the progress you have achieved?
Thanks in advance

**Comment by embray** [comment]
I'm working on writing the report.  I should add that although the title of this deliverable mentions "32bits", the 32-bit Windows install won't be available in time for the original deliverable due date due to technical challenges.  It's an open question whether it's worth delivering a 32-bit installer at all, and I'll address that question a bit in the report (my own opinion is that I think it *should* be done but only if an actual demand can be identified).

**Comment by embray** [comment]
Should I also write up a more comprehensive description of the deliverable, as in #62 ?  I'm also not sure what the "Nature" of the deliverable should be.  The primary deliverable is the software product itself--the Windows installer for Sage.  But the deliverable will also include a report (I assume?) since it's significant-enough work to write about I think.

**Comment by matthew-brett** [comment]
I don't know whether it's relevant, but we (Scipiers) recently cracked the Scipy build problem by using gfortran in a somewhat complicated way with MS Visual C - see https://github.com/scipy/scipy/pull/7616 and https://github.com/MacPython/scipy-wheels/pull/3 .  The only data I have quickly to hand on 32 bit Windows is from the [steam survey](http://store.steampowered.com/hwsurvey/) which says that Windows 7 32-bit is down to 4% of all Windows installs - but I suppose that Steam users are ahead of the main upgrade curve.  For example https://en.wikipedia.org/wiki/Usage_share_of_operating_systems has Windows 10 on 31% but Steam has 47% (as % of all Windows users).

**Comment by embray** [comment]
@matthew-brett Thanks for pointing out the Steam survey.  I was having trouble finding any current statistics of 32-bit vs 64-bit Windows installs.

The major issue with 32-bit support has nothing to do with any particular bugs in dependencies, which I could probably fix one way or another.  The main problem is a nasty cocktail of Cygwin, fork, and memory layout constraints on 32-bit :/

**Comment by matthew-brett** [comment]
That does sound like a particularly unattractive cocktail :(

**Comment by embray** [comment]
It would also be really nice, in cases where `fork()` is used, to replace it (on Cygwin) with the appropriate `spawn*()` variant, where possible.  In some cases `fork()` may be needed, but many fork/exec cases can be replaced with a `spawn()`, side-stepping (and slightly speeding up) many fork issues.

**Comment by nthiery** [comment]
Hi Erik!
Thanks for the update. We had mentionned 32bits in the original proposal because back then we expected it to be easier (Jean-Pierre had made much more progress for 32bits than 64bits). In fact, in some intermediate stage, we had two deliverables, an earlier one for 32bits, and a later one for 64bits.
Meanwhile things have changed, and the 64bits has indeed become the most important goal. 

So +1 for your approach (explain the history and document the focus on 64bit + implement 32bit later if there is an actual popular request for it).

**Comment by embray** [comment]
@nthiery Just to clarify--I *should* be writing a report, yes?  I'm a little confused, as in the proposal D3.1 and D3.7 have been "merged", but they're really pretty different, and we already published a report specifically for D3.1...

**Comment by nthiery** [comment]
Ah, right, I had forgotten that we had proposed to merge this deliverable with the other packaging/distribution deliverables.

Well, we will need anyway to report on the work here -- and that was a
lot of work you put -- which also had much impact outside of the
deliverable itself. This will take a comprehensive description of the
context, what was achieved, the aftermath, the sustainability, ... You
might as well write it while it's fresh.

Just don't worry too much about finalizing the introduction, since
it's likely that we will later complement it with material for the
other packaging/distribution actions. One option would be to write it
as a blog post from which we will later extract the material for the
general formal report.

Nature: for all our software oriented deliverables, we have used "other".

Thanks in advance!

**Comment by embray** [comment]
Okay, maybe I'll take what I have and put it in blog format for now.

**Comment by defeo** [comment]
I am confused too. It seems that this deliverable has not been merged in the latest amendment. @bpilorget, do you confirm?

If so, we should write a report. Fortunately, your [blog post](http://opendreamkit.org/2017/10/11/SageWindows/) is already an excellent writeup (btw, why does it not show in [the blog](http://opendreamkit.org/tag/blogpost)? I guess it needs a `blogpost` tag? @VivianePons ?)

**Comment by bpilorget** [comment]
HI @defeo . This deliverable was not merged with another one. So yes a report is due :)

**Comment by embray** [comment]
I can add all this no problem. We didn't include the screenshots thinking
that they padded the report length without adding much value. Maybe just
slightly fewer?

**Comment by nthiery** [comment]
>    I can add all this no problem.
>    We didn't include the screenshots thinking that they padded the
>    report length without adding much value.

They alternatively could be smaller. I got the impression that the
reviewer appreciate visual stuff, and it also makes the whole thing
more concrete. Since the report won't be printed in big quantities, if
at all, space is not expensive.

>    Maybe just slightly fewer?

Yup, or  alternatively half size.

Thanks!

**Comment by embray** [comment]
@nthiery I'm not sure what you mean by 'a mention of your "status upgrades" in these projects as a consequence of your work'

**Comment by embray** [comment]
@nthiery I've addressed all of the above except the "status upgrades" point I'm not clear on.  Also the section I added (ef99d195) on contributions to upstream projects feels a bit shoehorned in and I'm not quite sure what to do with it.  Suggestions for improvement, if any, are welcome.

**Comment by nthiery** [comment]
>    [1]@nthiery I've addressed all of the above except the "status
>    upgrades" point I'm not clear on. Also the section I added ([2]ef99d19)
>    on contributions to upstream projects feels a bit shoehorned in and I'm
>    not quite sure what to do with it. Suggestions for improvement, if any,
>    are welcome.

Thanks! I'll look at it.

**Comment by embray** [comment]
Done the last checkmark.

**Comment by embray** [comment]
@nthiery has asked me to maybe add the name and affiliation of my coauthor on PEP-539.  His name is Masayuki Yamamoto, but to be honest I don't know his exact affiliation.  @ma8ma, care to comment?  

For context, this is just a report I'm working on mentioning various work I've done toward the goal of porting SageMath to Windows, and I mentioned PEP-539 as part of that report.

**Comment by ma8ma** [comment]
Hi @embray,
I don't have relationship to any affiliations about PEP 539, but just my personal interest.

**Comment by embray** [comment]
Okay, thanks!

**Comment by nthiery** [comment]
Hi @embray,
I checked your commits since last time I looked at the report, and they sound good. Thanks!
Is there anything else you would like to update at this stage, or shall I submit the report as is?

**Comment by nthiery** [comment]
Ok! Report submitted. Time to close this one.

Thanks everyone, and in particular Erik and those who earlier lead the port to windows, for all the hard work and this great contribution to Sage; we had been waiting for it for 10 years!
