### ISSUE TITLE
D3.9: Semantic-aware Sage interface to GAP .

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#68]
- **WP3:** [Component Architecture](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP3)
- **Lead Institution:** University of Oxford
- **Due:** 2018-08-31 (month 36)
- **Nature:** Other
- **Task:** [T3.2](https://github.com/OpenDreamKit/OpenDreamKit/issues/51)

See page 43 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf).

Ongoing work on:
- https://github.com/nthiery/sage-gap-semantic-interface.
- [Sage Trac ticket #15276](https://trac.sagemath.org/ticket/15276)
- [Sage Trac ticket #18152](https://trac.sagemath.org/ticket/18152)
- [Sage Trac ticket #18158](https://trac.sagemath.org/ticket/18158)
- [Sage Trac ticket #18266](https://trac.sagemath.org/ticket/18266)
- [Sage Trac ticket #21020](https://trac.sagemath.org/ticket/21020)

See also our [paper submitted at CICM16](http://opendreamkit.org/activities/2016-03-21/)

cc: @nthiery, @slel, @kohlhase

**Comment by dimpase** [comment]
I wonder why Oxford is lead here; IMHO we are not taking part in this work (any more, since libGAP was put on hold).

**Comment by markuspf** [comment]
libGAP was put on hold? Why?

**Comment by dimpase** [comment]
@markuspf well, the one in Sagemath, that you didn't want to merge into GAP proper. I have not seen any replacements for it. Anyway, I don't see what Oxford should be doing in D3.9 any more.

**Comment by markuspf** [comment]
Of course, first of all, Oxford is in charge of this deliverable, because the proposal puts you in charge. This means you're responsible for it being delivered one way or another. You could ask for the deliverable to be reallocated if you feel that you will not be able to deliver it. For that we'll have to discuss with @nthiery.

There is a lot more to a semantic-aware interface between GAP and Sage than a libGAP.

First of course, libGAP exists, so one can use it:

* for prototyping a semantic-aware interface
* to find a GAP library API that is attractive to GAP developers.

(The main reason why libGAP is not just merged into GAP is that it has no visible benefit for GAP. This means it'd either be bitrotting, or put additional maintenance load on the GAP developers, yet, without benefit). I did say that I am working on an API to make GAP a library, and that I want it to make a good Jupyter kernel).

There are other ways of interfacing GAP and Sage as well. We used SCSCP/OpenMath in Bremen, and made great progress in describing the different approaches of the type descriptions in both systems to each other. This means you could approach @kohlhase and his team about progress there.
If we did not keep you in the loop enough about this, I will endeavour to notify you when something happens there.

**Comment by dimpase** [comment]
> The main reason  why libGAP is not just merged into GAP is that it has no visible benefit for GAP

I don't know what a "visible benefit" is, but a fact that using it you can embed GAP rather than communicate with it via pipes/sockets/files (as SCSCP does) is a huge deal for GAP. E.g. I recall @wbhart being interested in libGAP, as it would allow them to embed GAP into Nemo. 

Our experience with sockets vs library interfaces in Sagemath is that the latter is always much more robust and much faster. libGAP is important if you want to have GAP used more rather than less...

By the way, if you want a "monetary" benefit, one can perhaps  add libGAP to "Flagship Software Development Opportunity" EPSRC grant call application one hopefully is thinking about.

**Comment by dimpase** [comment]
I am obviously not qualified to lead the work on https://github.com/nthiery/sage-gap-semantic-interface (which already resulted in the CICM16 paper). This is interesting theoretical work, but in an area far from my interests and knowledge. While participating in developing the proposal I was under impression that at least part of this will be about libGAP.

**Comment by markuspf** [comment]
I, personally, as a GAP developer have (at this point in time) no interest in embedding GAP into Sage or Nemo. As someone on the ODK project, I have an interest in having a working Jupyter kernel.

If @wbhart, you, or anyone else want GAP to be embeddable into their software, they have to develop a suitable, non-intrusive solution to do that.

libGAP does exactly that at the moment, outside of the GAP code base.

You won't be able to offload the maintenance onto the GAP developers, because they have no benefit from it: They are happy to use GAP by itself, and embed other software into it, for example @wbhart's FLINT. 

If you want something from GAP, you have to contribute code, or at the very least argue the value and a sensible path, ideally on https://github.com/gap-system/gap. We discussed in Bremen that this is how open source mostly works. The absence of a merged libGAP shows that its value is currently not seen. In particular, without solid evidence, I do not believe that "libGAP is important if you want GAP to be used more rather than less".

More to the point of this issue though, if you don't feel qualified to deliver this deliverable, I think you should find someone who is, and is willing to.

**Comment by dimpase** [comment]
On 18 Aug 2016 2:39 pm, "Markus Pfeiffer" <notifications@github.com> wrote:
>
> I, personally, as a GAP developer have (at this point in time) no
interest in embedding GAP into Sage or Nemo. As someone on the ODK project,
I have an interest in having a working Jupyter kernel.
>
> If @wbhart, you, or anyone else want GAP to be embeddable into their
software, they have to develop a suitable, non-intrusive solution to do
that.
>
> libGAP does exactly that at the moment, outside of the GAP code base.
>
> You won't be able to offload the maintenance onto the GAP developers,
because they have no benefit from it: They are happy to use GAP by itself,
and embed other software into it, for example @wbhart's FLINT.
>
> If you want something from GAP, you have to contribute code,

I fully agree; however, libGAP is a contribution, too. A contribution that
you do not want, but which actually makes huge sense.  Or do you mean to
say that you want "better quality" code? Or  that you rather want to work
on it yourself? I think that was what you said when we talked in Bremen.

On the other hand you say now that you do not see libGAP's value. Thus I
don't see you working on a replacement for it, either.

> or at the very least argue the value and a sensible path, ideally on
https://github.com/gap-system/gap. We discussed in Bremen that this is how
open source mostly works. The absence of a merged libGAP shows that its
value is currently not seen.
> In particular, without solid evidence, I do not believe that "libGAP is
important if you want GAP to be used more rather than less".

Well, most of Sage's use of GAP has been converted to use libGAP's
interface. Because it is much more efficient than sockets. Or do you want
to see benchmarks, you do not trust me that we did run a lot of them and
did come to this point of view?
Well, you mentioned that you cannot even run Sage on your machines, and
didn't  reply to the question why this is the case.

>
> More to the point of this issue though, if you don't feel qualified to
deliver this deliverable, I think you should find someone who is, and is
willing to.

The contribution I had in mind for this deliverable, libGAP, turns out to
be a nonstarter. As you imagine, I am not going to fork GAP to produce it.
And I cannot deliver a deliverable in which I do not understand anything at
all. It is not how I "feel" about it, it is for the best of the ODK project
that someone who knows how to sell the contributions being done here to
step in and replace me.

**Comment by videlec** [comment]
@nthiery @dimpase @markuspf The libGAP thing is indeed mostly disjoint from the semantic-aware interface. I am willing to take charge of the deliverable. Is that OK?

@markuspf you wrote "libGAP is important if you want GAP to be used more rather than less". Do you imply that using libGAP would not be using GAP? Sage is likely to use more and more of GAP features through libGAP (e.g. the universal cyclotomic field). However this is transparent to Sage users: they don't know they are using GAP. There has been some attempt to have a proper citation mechanism in Sage (e.g. https://trac.sagemath.org/ticket/3317) but this is on hold.

Note: the link to the CICM16 paper (at http://opendreamkit.org/activities/2016-03-21/) does not work.

**Comment by markuspf** [comment]
libGAP is not a contribution to GAP: there are no working pull-requests, there was no (visible to me) discussion how it fits. libGAP is a project done in the GPL spirit, it is maybe a contribution to software infrastructure. It is not a contribution to GAP, because it is not a part of GAP (quite to the contrary: GAP is a part of libGAP).

I suggested in Bremen that I am working on a way to interface GAP as a library with external programs that is more agreeable with how GAP developers see it. Not necessarily because I desperately want to, but because there seems to be a demand (even one I have myself, namely the Jupyter kernel). 
Maybe you want to use libGAP, which is fine with me, but it (very likely) won't get merged into the GAP source-base proper. I will also happily *collaborate* to make it more agreeable, if that is a path people want to take.
I have elaborated this point enough now, so I am going to stop there.

@videlec The statement about "libGAP is important if you want GAP to be used more rather than less" is from @dimpase, and what is probably meant is "if you want GAP to be used more conveniently in Sage", and while that is a very understandable goal of the Sage developers, it is not a priority of mine.

Getting back to the point, @videlec maybe we start by saying what the goals for this deliverable now *actually* are? It seems to me that this is more a project driven by Sage. I can support with the GAP side.

We need someone to be formally in charge, I have no objections to it being @videlec or @dimpase 

(Also, I think Sage should make the citation mechanism work and give credit (or miscredit), where it's due, to GAP).

**Comment by videlec** [comment]
@markuspf  The goals of the deliverable are pretty clear to me: we want conversion back and forth between GAP and Sage. The slow way of doing this is to use serialization (e.g. MMT). But it is currently not satisfactory (at least on the Sage side) because it is slow. Instead, the approach of https://github.com/nthiery/sage-gap-semantic-interface is to add structures to the GAP-handles in Sage making it fits with the Element/Parent/Category stuff we use in Sage.

**Comment by markuspf** [comment]
The tools we are developing in collaboration with Bremen are quite a bit more than serialisation through MMT: They are supposed to provide an automatic way to translate the type information between the systems.
You can of course get type information from GAP objects, but that is GAP type information. If you go the "pedestrian" way (for lack of a better word) you can of course just attach some typing information to handles by hand.
MitM would allow you to do these translations automatically (regardless of the backend you're using).

Of course in the interest of doing "something" it might be better to do some pedestrian stuff first, premature abstraction is the root of all evil after all.

**Comment by wbhart** [comment]
I have been mentioned a few times here. Just to update everyone: I will not
be working directly on putting Gap into Julia/Nemo. I believe the task has
been assigned to someone else within our collaboration (not the ODK
collaboration). Also, Nemo was not conceived of when ODK was conceived, so
I think it is a stretch to use it as a justification for anything ODK
related at the moment.

I'm personally more in favour of a libGap type approach for interfacing to
Gap. But it won't be my decision in the end.

There has also been some talk about writing a Gap in Julia that is capable
of loading existing Gap files. So it's not totally clear yet what the
ultimate long term strategy is for interfacing Gap and Julia. Of course it
goes without saying that we don't expect the Gap people to write code for
us.

Bill.

**Comment by defeo** [comment]
Sorry for jumping in late. I also wonder why Oxford is lead here, although I'm sure @dimpase can give very good insights into this deliverable. Thanks Dima for raising the issue.

I remember that part of the proposal being written mostly by @nthiery, and, as the deliverable description says, he and @slel have already done some work in that direction. We might want to wait for their feedback (I know Nicolas is on vacation until next week) before deciding what must be delivered.
And there is no reason to rush a decision here, month 36 is still far away, and the content of this deliverable will probably get influenced by progress on others.

**Comment by dimpase** [comment]
On 18 Aug 2016 4:46 pm, "Markus Pfeiffer" <notifications@github.com> wrote:
>
> libGAP is not a contribution to GAP: there are no working pull-requests,
there was no (visible to me) discussion how it fits. libGAP is a project
done in the GPL spirit, it is maybe a contribution to software
infrastructure. It is not a contribution to GAP, because it is not a part
of GAP (quite to the contrary: GAP is a part of libGAP).
>

of course after St Andrews meeting I assumed that something would come from
GAP side regarding the way you would like to proceed with merging libGAP
into GAP proper. But nothing happened, these were just empty promises.
Hearing that GAP is a part of libGAP in terms of functionality is also very
strange, for it is more or less just another interface to the core GAP
system.

> I suggested in Bremen that I am working on a way to interface GAP as a
library with external programs that is more agreeable with how GAP
developers see it. Not necessarily because I desperately want to, but
because there seems to be a demand (even one I have myself, namely the
Jupyter kernel).
> Maybe you want to use libGAP, which is fine with me, but it (very likely)
won't get merged into the GAP source-base proper. I will also happily
collaborate to make it more agreeable, if that is a path people want to
take.

I would be happy to contribute to a "proper" (from your  point of view)
replacement of libGAP. I suppose this would entail splitting GAP into a
dynamic library and frontend(s).
Is this the plan?

> I have elaborated this point enough now, so I am going to stop there.
>
> @videlec The statement about "libGAP is important if you want GAP to be
used more rather than less" is from @dimpase, and what is probably meant is
"if you want GAP to be used more conveniently in Sage", and while that is a
very understandable goal of the Sage developers, it is not a priority of
mine.

No, in fact libGAP is hardly a Sage-centric project! For it allows for
efficient embedding of GAP into any program that can do plain C library
runtime-interfaces: C/C++, Julia, Haskell, Python, probably a dozen other
major systems. And by efficient I mean that you can afford to use it in
code that needs manipulating groups fast, such as e.g.
graph isomorphism algorithms implementations.

Don't tell me that this is not something that would not promote wider use
of GAP :-)

>
> Getting back to the point, @videlec maybe we start by saying what the
goals for this deliverable now actually are? It seems to me that this is
more a project driven by Sage. I can support with the GAP side.
>
> We need someone to be formally in charge, I have no objections to it
being @videlec or @dimpase
>
> (Also, I think Sage should make the citation mechanism work and give
credit (or miscredit), where it's due, to GAP).
>

**Comment by markuspf** [comment]
@dimapase I suggest we take this discussion off this issue, as it has gone off-topic for this deliverable. Please contact me via Email or write to the GAP development mailing with constructive suggestions.

**Comment by dimpase** [comment]
@markuspf : I've sent you an email on "libGAP 2.0". Hopefully we could work out details.

**Comment by UrsulaMartin** [comment]
This deliverable is indeed Oxford's responsibility, and as requested the discussion is being taken off line, involving, initially, the Oxford team and the leaders of WP3. Please contact myself or Dima Pasechnik with any further input.  Ursula Martin

**Comment by nthiery** [comment]
Sorry, for jumping in late; as @defeo mentionned, I am just back from vacations.

If everybody agrees, I am happy to take officially the lead for this deliverable: I initiated it in the proposal, need it personnally for my research, and worked on it with @slel (and the WP6 team).I don't remember exactly why we had put Oxford as official lead here: presumably just because @dimpase is one of the most knowledgable person in our consortium about Sage-GAP communication. If Oxford wishes so, we can update the grant agreement accordingly (transfering the lead from Oxford to ParisSud) at the occasion of the next amendment.

I believe the libgap discussion is indeed essentially irrelevant to this deliverable, and would be tempted to remove the relevant comments above from this issue to not polute it. What do you think?

**Comment by UrsulaMartin** [comment]
Nicolas

Thank you for your interjection - I will respond more fully by the end of the morning.

Ursula

**Comment by dimpase** [comment]
@nthiery : how about we move libGAP-related discussion to another issue?

**Comment by dimpase** [comment]
@nthiery : if you rather prefer to leave it as it is, with Oxford in charge, I am fine with it (provided you do the work :-)). Administratively this is probably the easiest for everyone.

**Comment by UrsulaMartin** [comment]
I promised to respond more fully by the end of the morning, though I do not have too much to contribute yet. 

Intellectually and scientifically, Nicolas's offer is most welcome. However any change in the contractual, managerial or funding arrangements for the Oxford contribution to ODK need to be determined by those responsible, according to the official procedures of the University and the EU.  I'm somewhat old-school - the operational details of these will be discussed privately, and not on the ODK public website.  

Ursula Martin

Ursula

**Comment by embray** [comment]
Just piping in to say I agree with @dimpase 
>> The main reason why libGAP is not just merged into GAP is that it has no visible benefit for GAP

> I don't know what a "visible benefit" is, but a fact that using it you can embed GAP rather than communicate with it via pipes/sockets/files (as SCSCP does) is a huge deal for GAP

Having a library interface (*any library interface*) is better than none in terms of software design.  I think good software design is a benefit in its own right sometimes.  If there are ideas for a *better* library interface that should certainly be entertained.  Apologies if this is already far off-topic.

**Comment by nthiery** [comment]
@UrsulaMartin, @dimpase: no need to transfer PM's to Orsay; I was anyway planning to work on this deliverable and Dima already has plenty on his plate. From an administrative point of view, this should be no issue as the grant agreement does not specify how many PM's each site spends on each deliverable.

**Comment by UrsulaMartin** [comment]
To sign off this thread - Oxford and Paris have now agreed between us that Paris will take over deliverable 3.9, and not require the transfer of any person months from Oxford. Nicolas will take care of the necessary EU approvals. Any work done by Oxford on the deliverable will be part of the usual day-to-day collaborative development workflow and Nicolas doesn't at present foresee a need to formalise it.

**Comment by JohnCremona** [comment]
On 26 August 2016 at 08:59, UrsulaMartin <notifications@github.com> wrote:

> To sign off this thread - Oxford and Paris have now agreed between us that
> Paris will take over deliverable 3.9, and not require the transfer of any
> person months from Oxford. Nicolas will take care of the necessary EU
> approvals. Any work done by Oxford on the deliverable will be part of the
> usual day-to-day collaborative development workflow and Nicolas doesn't at
> present foresee a need to formalise it.
>

Thanks for reporting back on the outcome.  I agree that such bilateral
arrangements are best sorted out between the two parties concerned
(including the centre when Paris is not one of the parties), with wider
concensus only being required if a transfer of funds is being proposed.

**Comment by bpilorget** [comment]
#68 and #141 were merged into #142 after the 3rd amendment to the contract.
