### ISSUE TITLE
T5.1: PARI

### ISSUE THREAD

**Issue by minrk** [OpenDreamKit/OpenDreamKit#99]
- **WP5:** [High Performance Mathematical Computing](https://github.com/OpenDreamKit/OpenDreamKit/tree/master/WP5)
- **Lead Institution:** CNRS
- **Partners:** None
- **Work phases:** 0-48!0.5
- **Deliverables:** D5.10 (#108) and D5.16 (#114 )

See page 49 of the [proposal](https://github.com/OpenDreamKit/OpenDreamKit/raw/master/Proposal/proposal-www.pdf) for the full description.

**Comment by ClementPernet** [comment]
@KBelabas  @videlec  : could you feed me with some status update on this task. Even if the delivery is scheduled for next year, we need to write a status update in D1.5 (issue #21 ) of this fall's report. This is urgent (we need to write this update by thursday Aug. 30th).
Best would be if you could edit the report of D1.5 with these updates.

**Comment by ClementPernet** [comment]
The report of D1.5 is at https://github.com/OpenDreamKit/OpenDreamKit/blob/master/WP1/D1.5/WP5.tex#L53

**Comment by KBelabas** [comment]
Hi Clément,

* Clément Pernet [2018-08-29 15:07]:
> @KBelabas  @videlec  : could you feed me with some status update on this task. Even if the delivery is scheduled for next year, we need to write a status update in D1.5 (issue #21 ) of this fall's report. This is urgent (we need to write this update by thursday Aug. 30th).
> Best would be if you could edit the report of D1.5 with these updates.

My comment from last year for issue #108
  https://github.com/OpenDreamKit/OpenDreamKit/issues/108
is still essentially accurate.

I'm pasting an updated version below now that 'master' has been released
as PARI-2.11. Is this suitable ? Should need to edit D1.5 myself ?
[It's going to be hard, I'm behind schedule for other short-term deadlines.] 

Executive summary: basic deliverables are done, we are working on
extending coverage where it makes sense.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
 Assigned #108 to @KBelabas.
 D5.10: Devise a generic
 parallelisation engine for PARI and use it to prototype selected functions
 (integer factorisation, discrete logarithm, modular polynomials) (#108)
 [merged with D5.16 in the revised workplan].

 D5.16: PARI suite release ( libpari , GP and GP2C ) that fully support
 parallelisation allowing individual implementations to scale gracefully
 between single core / multicore / massively parallel machines
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

The generic engine was written and finalized in 2015 and 2016 and is in
production since PARI-2.9 (released 11/2016), it supports sequential
evaluation (no parallelism), POSIX threads and MPI within the same code
base. Development work since then is targetted at using the engine
wherever it makes sense in the code base. The current situation (PARI-2.11,
released 07/2018) includes:
- fast (~linear time) Chinese remaindering
- fast linear algebra over Q and cyclotomic fields, a critical component
  of the new "Modular Forms" package
- polynomial resultant in Z[X] via Chinese remainders
- computation of classical modular polynomials for about 20 classical
  invariants (j, Weber functions, small eta quotients...)
- discrete logarithm over finite fields (prime fields and F_{p^e}
  for word-sized prime p)
- polynomial resultant in Z[X] x Z[X,Y] via Chinese remainders / evaluation
- APRCL primality proof

TODO: ECPP, integer factorization engines, class group & units computations,
...

Compared to the pre-existing sequential code, the parallel version
adds about 15 extra lines of C on average (conveniently encapsulated in
a separate "worker" object). As usual in "embarassingly parallel" code,
the measured speedup is essentially linear in the number of available cores.

The resulting gp binary has been successfully crashtested by a panel of
users during the 2017 PARI/GP Atelier in Lyon: basically, substituting
the 'Configure' instruction by 'Configure --mt=pthreads' before
compilation transparently yields the expected speedups for the target
functions on participants dual-core laptops.
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


Cheers,

    K.B.
--
Karim Belabas, IMB (UMR 5251)  Tel: (+33) (0)5 40 00 26 17
Universite de Bordeaux         Fax: (+33) (0)5 40 00 21 23
351, cours de la Liberation    http://www.math.u-bordeaux.fr/~kbelabas/
F-33405 Talence (France)       http://pari.math.u-bordeaux.fr/  [PARI/GP]
`

**Comment by ClementPernet** [comment]
Thanks @KBelabas . I'll update D1.5 myself with your input.
What do you mean in the TODO: is this a list of things that you are still working on for this deliverable D5.16, or is it a todo for this text in D1.5 (waiting to elaborate on these topics)?

**Comment by jdemeyer** [comment]
Just so you know: in the report of D4.10 (#84) I am showing an example parallel computation using cypari2:
```
In [1]: from cypari2 import Pari; pari = Pari()

In [2]: pari.default("nbthreads", 2)

In [3]: L = [2**i - 1 for i in range(1, 201)]

In [4]: %time res = pari.parapply("factor", L)
CPU times: user 6.76 s, sys: 170 ms, total: 6.93 s
Wall time: 3.6 s
```
I also refer to T5.1 in the report.

**Comment by KBelabas** [comment]
* Clément Pernet [2018-08-30 11:07]:
> Thanks @KBelabas . I'll update D1.5 myself with your input.
> What do you mean in the TODO: is this a list of things that you are
> still working on for this deliverable D5.16, or is it a todo for this
> text in D1.5 (waiting to elaborate on these topics)?

It's in the list of things that *could* be included in deliverable D5.16.
Not sure we'll do it in the end:

0) we're currently not working on it but rather focussing on exploiting
the new implementations in new modules [ just relying on faster internal
linear algebra, not parallelizing new stuff ]

1) there are non trivial obstacles in the code base: the sequential
version of factorization / class group & units is a big mess already
(ECPP is OK but harder to parallelize meaningfully...)

2) naive external parallelization is often sufficient [ treat N similar
problems by parallelizing your external loop instead of going all on a
single instance to (usually fail to) make it N times faster ]

Cheers,

    K.B.
--
Karim Belabas, IMB (UMR 5251)  Tel: (+33) (0)5 40 00 26 17
Universite de Bordeaux         Fax: (+33) (0)5 40 00 21 23
351, cours de la Liberation    http://www.math.u-bordeaux.fr/~kbelabas/
F-33405 Talence (France)       http://pari.math.u-bordeaux.fr/  [PARI/GP]
`
